name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    # Autenticaci√≥n con tu service account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Instalar gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    # Configurar Docker para Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    # Construir y subir imagen
    - name: Build and push Docker image
      run: |
        IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/myrepo/webcolegio:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE

    # Desplegar en Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: webcolegio     # NOMBRE DEL SERVICIO en Cloud Run
        image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/myrepo/webcolegio:${{ github.sha }}
        region: us-central1
        allow_unauthenticated: true
